log_level: WARNING  # TRACE WARNING

task:
    eda_mode: False  # True False

experiment:
    model: unet  # resnet
    name: ${experiment.model}

paths:
    roots:
        ws: /home/stud/ath/ath_ws/others # /home/stud/ath/ath_ws/others  D:/code
        project: ${paths.roots.ws}/document_denoiser
        output: ${paths.roots.project}/output
        data: ${paths.roots.project}/data

    output:
        logs: ${paths.roots.output}/${experiment.name}/logs
        checkpoints: ${paths.roots.output}/${experiment.name}/checkpoints
        train_images: ${paths.roots.output}/${experiment.name}/images/train
        val_images: ${paths.roots.output}/${experiment.name}/images/val
        test_images: ${paths.roots.output}/${experiment.name}/images/test

image:
    image_shape: [256, 256]

train:
    train_batch_size: 4
    val_batch_size: 4

    fast_dev_run: False  # True False
    overfit_batches: 0

    patience: 5
    max_epochs: 50
    check_val_every_n_epoch: 5
    num_sanity_val_steps: 1
    log_every_n_steps: 1
    accumulate_grad_batches: 4
    learning_rate: 1e-4

val:
    save_count: 6

test:
    batch_size: 4

loggers:
     - tensorboard
#    - neptune




